<a href="https://colab.research.google.com/github/OlatundeEso/Resume/blob/main/My_Spam_Detector_With_Deep_Learning_27092023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('/content/Dataset.csv', encoding='latin1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df.head(2)

v1                                                 v2 Unnamed: 2  \
0  ham  Go until jurong point, crazy.. Available only ...        NaN   
1  ham                      Ok lar... Joking wif u oni...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN

In [4]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [5]:
df.columns = ['Category', 'Message', 1, 2, 3]

In [6]:
df.head()

Category                                            Message    1    2    3
0      ham  Go until jurong point, crazy.. Available only ...  NaN  NaN  NaN
1      ham                      Ok lar... Joking wif u oni...  NaN  NaN  NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...  NaN  NaN  NaN
3      ham  U dun say so early hor... U c already then say...  NaN  NaN  NaN
4      ham  Nah I don't think he goes to usf, he lives aro...  NaN  NaN  NaN

In [7]:
df.columns

Index(['Category', 'Message', 1, 2, 3], dtype='object')

In [8]:
df = df.drop([1,2,3], axis = 1)

In [9]:
df.head(2)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...

In [10]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df['Spam'].head()

0    0
1    0
2    1
3    0
4    0
Name: Spam, dtype: int64

In [12]:
df['Spam'].sample(5)

1899    0
573     0
1268    1
48      0
3792    0
Name: Spam, dtype: int64

In [13]:
import numpy as np
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split( df['Message'], df['Spam'], test_size=0.2, random_state=42)

In [15]:
X_train.head()

3918    I wish! I don't think its gonna snow that much...
3986    Ringtone Club: Gr8 new polys direct to your mo...
2758              What time. I‰Û÷m out until prob 3 or so
4796    Santa calling! Would your little ones like a c...
4503    She told to hr that he want posting in chennai...
Name: Message, dtype: object

In [16]:
y_train.head()

3918    0
3986    1
2758    0
4796    1
4503    0
Name: Spam, dtype: int64

In [17]:
len(df[df['Spam'] == 1])

747

In [18]:
len(df[df['Spam'] == 0])

4821

In [19]:
df['Spam'].value_counts()

0    4821
1     747
Name: Spam, dtype: int64

In [20]:
# Now we need to downsample since this data is not balanced. We will need to downsample the ham figures
downsample_ham = df[df['Spam'] == 0].sample(len(df[df['Spam'] == 1]))
downsample_ham

Category                                            Message  Spam
5447      ham              So that takes away some money worries     0
4272      ham  Kind of. Just missed train cos of asthma attac...     0
2713      ham  Nope i'm not drivin... I neva develop da photo...     0
1974      ham  Thats cool. Where should i cum? On you or in y...     0
3803      ham  No dude, its not fake..my frnds got money, tht...     0
...       ...                                                ...   ...
4931      ham              Match started.india  &lt;#&gt;  for 2     0
3066      ham                            Ok. So april. Cant wait     0
316       ham  Hmmm... Guess we can go 4 kb n power yoga... H...     0
1912      ham  For real tho this sucks. I can't even cook my ...     0
203       ham                           Goodmorning sleeping ga.     0

[747 rows x 3 columns]

In [21]:
downsample_ham.shape

(747, 3)

In [22]:
downsample_ham.head(3)

Category                                            Message  Spam
5447      ham              So that takes away some money worries     0
4272      ham  Kind of. Just missed train cos of asthma attac...     0
2713      ham  Nope i'm not drivin... I neva develop da photo...     0

In [23]:
downsample_ham.shape

(747, 3)

In [24]:
df['Spam'].value_counts()

0    4821
1     747
Name: Spam, dtype: int64

In [25]:
df_balanced = pd.concat([downsample_ham, df[df['Spam'] == 1]])
df_balanced.head()

Category                                            Message  Spam
5447      ham              So that takes away some money worries     0
4272      ham  Kind of. Just missed train cos of asthma attac...     0
2713      ham  Nope i'm not drivin... I neva develop da photo...     0
1974      ham  Thats cool. Where should i cum? On you or in y...     0
3803      ham  No dude, its not fake..my frnds got money, tht...     0

In [26]:
df_balanced.shape

(1494, 3)

In [27]:
df_balanced['Spam'].value_counts()

0    747
1    747
Name: Spam, dtype: int64

In [28]:
df_balanced = df_balanced.sample(frac = 1.0)
df_balanced

Category                                            Message  Spam
1195     spam  You have 1 new voicemail. Please call 08719181503     1
4438      ham               i want to grasp your pretty booty :)     0
4246     spam  Text PASS to 69669 to collect your polyphonic ...     1
5228     spam  PRIVATE! Your 2003 Account Statement for <fone...     1
2808      ham  Oh yeah I forgot. U can only take 2 out shoppi...     0
...       ...                                                ...   ...
388      spam  4mths half price Orange line rental & latest c...     1
3740     spam                                      2/2 146tf150p     1
2741     spam  I don't know u and u don't know me. Send CHAT ...     1
5537     spam  Want explicit SEX in 30 secs? Ring 02073162414...     1
742       ham  Just got up. have to be out of the room very s...     0

[1494 rows x 3 columns]

In [66]:
len(X_train)

4454

In [67]:
len(y_train)

4454

In [72]:
len(y_test)

1114

In [69]:
len(X_test)

1114

In [29]:
df_balanced.loc[683]['Message']

"Hi I'm sue. I am 20 years old and work as a lapdancer. I love sex. Text me live - I'm i my bedroom now. text SUE to 89555. By TextOperator G2 1DA 150ppmsg 18+"

In [30]:
X_train, X_test, y_train, y_test = train_test_split( df['Message'], df['Spam'], test_size=0.2, random_state=42)

In [31]:
X_train[56]

'Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! '

In [32]:
y_train[56]

1

In [33]:
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocessor_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [34]:
# Creating the Layers for the Preprocessor and the Encoder
# We would create a layer for each:

In [35]:
import tensorflow as tf
import tensorflow_hub as hub
!pip install tensorflow_text
import tensorflow_text as text


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 52.9 MB/s eta 0:00:00


In [36]:
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)

In [37]:
text_input

<KerasTensor: shape=(None,) dtype=string (created by layer 'input_1')>

In [38]:
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocessor_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [39]:
preprocessor = hub.KerasLayer(preprocessor_url)
preprocessor

In [40]:
bert_encoder = hub.KerasLayer(encoder_url)

In [41]:
bert_encoder

In [42]:
preprocessed_text = preprocessor(text_input)

Now Let us Inspect the Output of the Preprocessed Text Outputs

In [43]:
preprocessed_text.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [44]:
preprocessed_text['input_word_ids']

<KerasTensor: shape=(None, 128) dtype=int32 (created by layer 'keras_layer')>

In [45]:
preprocessed_text['input_mask']

<KerasTensor: shape=(None, 128) dtype=int32 (created by layer 'keras_layer')>

In [46]:
bert_encoder_output = bert_encoder(preprocessed_text)
bert_encoder_output

{'default': <KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'keras_layer_1')>,
 'pooled_output': <KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'keras_layer_1')>,
 'encoder_outputs': [<KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by 

In [47]:
bert_all_outputs = bert_encoder_output.keys()
bert_all_outputs

dict_keys(['default', 'pooled_output', 'encoder_outputs', 'sequence_output'])

In [48]:
bert_output_2use = bert_encoder_output['pooled_output']
bert_output_2use

<KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'keras_layer_1')>

In [49]:
layer1 = tf.keras.layers.Dropout(0.1, name = "dropout")(bert_output_2use)


In [50]:
layer2 = tf.keras.layers.Dense(1, activation = "sigmoid", name="output")(layer1)

In [51]:
model = tf.keras.Model(inputs=[text_input], outputs=[layer2])

In [52]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None,)]                    0         []                            
                                                                                                  
 keras_layer (KerasLayer)    {'input_type_ids': (None,    0         ['input_1[0][0]']             
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_word_ids': (None,                                           
                              128)}                                                               
                                                                                              

In [53]:
model.compile(optimizer = "adam", loss="binary_crossentropy", metrics = ["accuracy"])

In [54]:
model.fit(X_train, y_train, epochs = 10)

Epoch 1/10
140/140 [==============================] - 59s 327ms/step - loss: 0.3474 - accuracy: 0.8657
Epoch 2/10
140/140 [==============================] - 47s 337ms/step - loss: 0.2416 - accuracy: 0.8900
Epoch 3/10
140/140 [==============================] - 48s 340ms/step - loss: 0.2011 - accuracy: 0.9185
Epoch 4/10
140/140 [==============================] - 47s 338ms/step - loss: 0.1720 - accuracy: 0.9344
Epoch 5/10
140/140 [==============================] - 48s 340ms/step - loss: 0.1560 - accuracy: 0.9436
Epoch 6/10
140/140 [==============================] - 47s 339ms/step - loss: 0.1414 - accuracy: 0.9484
Epoch 7/10
140/140 [==============================] - 48s 340ms/step - loss: 0.1358 - accuracy: 0.9535
Epoch 8/10
140/140 [==============================] - 47s 338ms/step - loss: 0.1241 - accuracy: 0.9616
Epoch 9/10
140/140 [==============================] - 47s 338ms/step - loss: 0.1162 - accuracy: 0.9625
Epoch 10/10
140/140 [==============================] - 47s 338ms/step - l

In [73]:
model.evaluate(X_test, y_test)

35/35 [==============================] - 13s 321ms/step - loss: 0.1125 - accuracy: 0.9776


[0.1125103160738945, 0.9775583744049072]

Now Let us Inference this Model

In [99]:
check_message = [
    "I have a lucrative business opportunity in your country to share with you. Please contact here: dominichibz2022@aol.com  for the full details",
    "$909900, just click here and win amazing price. I inherit so much from my parents and willing to share with you",
    "You're eligible for business-only pricing, Did you know you can get instant savings on supplies for work when you shop on Amazon Business?",
    "Your Subscription Of McAfee Total Protection Has Expired on Tue,26 Sep-2023. After the  expiry date has passed your Device Mac/Windows will become susceptible to many different virus theats.",
    "This e-mail has been issued to you in order to Officially inform you that we have completed an investigation on an International Payment in which was issued to you by an International Lottery Company. With the help of our newly developed technology (International Monitoring Network System) we discovered that your e-mail address was automatically selected by an Online Balloting System, this has legally won you the sum of $2.4million USD from a Lottery Company outside the United States of America",
    "Dear Customer, Your current plan has expired. Upgrade to National Plus Extra plan and get 30GB of data, unlimited calls and texts, and 100 international mins at £12 for 30 days. EU roaming included. To purchase,  click below.",
    "Thank you for choosing one of our credit cards. Your card is being produced now and will be with you within 7 working days.When your new credit card arrives, please sign it and follow the simple steps to activate it as soon as possible. Once activated, you’ll be able to start using it immediately. If you set up any balance transfers as part of your application, we’ll send you a separate email confirming their progress",
    "I am really hungry and would love your assistance with whatever you can support with, thank you"
]

In [100]:
check_message

['I have a lucrative business opportunity in your country to share with you. Please contact here: dominichibz2022@aol.com  for the full details',
 '$909900, just click here and win amazing price. I inherit so much from my parents and willing to share with you',
 "You're eligible for business-only pricing, Did you know you can get instant savings on supplies for work when you shop on Amazon Business?",
 'Your Subscription Of McAfee Total Protection Has Expired on Tue,26 Sep-2023. After the  expiry date has passed your Device Mac/Windows will become susceptible to many different virus theats.',
 'This e-mail has been issued to you in order to Officially inform you that we have completed an investigation on an International Payment in which was issued to you by an International Lottery Company. With the help of our newly developed technology (International Monitoring Network System) we discovered that your e-mail address was automatically selected by an Online Balloting System, this has l

In [101]:
len(check_message)

8

In [102]:
model.predict(check_message)

1/1 [==============================] - 0s 59ms/step


array([[0.6952237 ],
       [0.5422844 ],
       [0.38054436],
       [0.8248301 ],
       [0.93322664],
       [0.9433428 ],
       [0.90898293],
       [0.09720045]], dtype=float32)

In [55]:
your_message = "I am really hungry"
your_message

'I am really hungry'

In [56]:
# Create a Test "Contextualized Embedder"
def get_sentence_embedding(your_message):
  preprocessed_message = preprocessor(your_message)
  return bert_encoder(preprocessed_message)['pooled_output']

In [57]:
get_sentence_embedding(["I am not a woman", "I love playing football"])

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8272173 , -0.27784848,  0.21502087, ...,  0.16865215,
        -0.56069   ,  0.89553267],
       [-0.8815788 , -0.44962737, -0.7034719 , ..., -0.41828567,
        -0.66904926,  0.908172  ]], dtype=float32)>

In [58]:
from sklearn.metrics.pairwise import cosine_similarity


In [59]:
# Create a Sentence Embedding Output Solution
def get_sentence_embedding(your_message_a, your_message_b):
  preprocessed_message_a = preprocessor(your_message_a)
  preprocessed_message_b = preprocessor(your_message_b)
  bert_output_a = bert_encoder(preprocessed_message_a)['pooled_output']
  bert_output_b = bert_encoder(preprocessed_message_b)['pooled_output']
  sentence1 = bert_output_a
  sentence2 = bert_output_b
  return sentence1, sentence2


In [60]:
# Create a Sentence Comparison Function
def get_sentence_comparison(your_message_a, your_message_b):
  preprocessed_message_a = preprocessor(your_message_a)
  preprocessed_message_b = preprocessor(your_message_b)
  bert_output_a = bert_encoder(preprocessed_message_a)['pooled_output']
  bert_output_b = bert_encoder(preprocessed_message_b)['pooled_output']
  sentence1 = bert_output_a
  sentence2 = bert_output_b
  return cosine_similarity(sentence1, sentence2)

In [61]:
get_sentence_comparison(["Samsung"], ["faeces"])

array([[0.9338934]], dtype=float32)

In [62]:
# Create a Combined Sentence Comparison Function
def get_sentence_embedding_comparison(your_message):
  preprocessed_message = preprocessor(your_message)
  bert_output = bert_encoder(preprocessed_message)['pooled_output']
  sentence_embedding4c = bert_output
  return sentence_embedding4c

In [63]:
your_message = (["Apple", "Mango", "Orange", "Alexander the Great", "Elon Musk the Entrepreneur", "Joe Biden", "dog", "cat", "lion", "I am hungry", "I am full", "King Herod", "The Death of Jesus Christ", "shoe", "wisdom", "foolishness", "This is a great movie", "This is a very poor and uninteresting movie"])
your_message

['Apple',
 'Mango',
 'Orange',
 'Alexander the Great',
 'Elon Musk the Entrepreneur',
 'Joe Biden',
 'dog',
 'cat',
 'lion',
 'I am hungry',
 'I am full',
 'King Herod',
 'The Death of Jesus Christ',
 'shoe',
 'wisdom',
 'foolishness',
 'This is a great movie',
 'This is a very poor and uninteresting movie']

In [64]:
e = get_sentence_embedding_comparison(your_message)
e

<tf.Tensor: shape=(18, 768), dtype=float32, numpy=
array([[-0.8196459 , -0.296096  ,  0.20951748, ...,  0.2559338 ,
        -0.58742994,  0.8434557 ],
       [-0.7128861 , -0.15463905,  0.38401666, ...,  0.35278705,
        -0.5099134 ,  0.73474085],
       [-0.83630776, -0.23830132,  0.38453603, ...,  0.45564777,
        -0.6078617 ,  0.827889  ],
       ...,
       [-0.7764665 , -0.19767635,  0.17361054, ...,  0.19300213,
        -0.58053976,  0.77596295],
       [-0.9377887 , -0.44213954, -0.4914478 , ..., -0.1601311 ,
        -0.69003016,  0.93813455],
       [-0.89951044, -0.5367922 , -0.866538  , ..., -0.74519396,
        -0.6771414 ,  0.9041538 ]], dtype=float32)>

In [94]:
cosine_similarity([e[3]], [e[16]])

array([[0.11302805]], dtype=float32)